kind: SecretProviderClass
apiVersion: secrets-store.csi.x-k8s.io/v1
metadata:
  name: {{ include "azure-advisor-helm.fullname" . }}-spc
spec:
  provider: azure
  parameters:
    useworkloadIdentity: "true"
    tenantID: "{{ .Values.keyVault.tenantId }}"
    keyvaultName: "{{ .Values.keyVault.kvname }}"
    objects: |
      array: 
        - |
          objectName: cosmos-endpoint
          objectType: secret
        - |
          objectName: cosmos-key
          objectType: secret
        - |
          objectName: azure-ai-endpoint
          objectType: secret
        - |
          objectName: azure-ai-key
          objectType: secret
